#pragma once

#ifndef CONSTS_HEADER_FILE_H
#define CONSTS_HEADER_FILE_H

#include "stdafx.h"


#define _GLOBAL_CODECS_ENABLED "PCMA/8000/1 PCMU/8000/1"
#define FOREGROUND_WHITE (FOREGROUND_RED | FOREGROUND_BLUE | FOREGROUND_GREEN)
#define DEFAULT_UA_STRING "TinyPhone Pjsua2 v0"

#endif